---
title: "Taller descriptivos univariados"
author: "Nicolás Godoy Márquez"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F )
```

```{r packages}
pacman::p_load(tidyverse,
               sjmisc, 
               sjPlot,
               ggrepel, #Para evitar solapamientos en grafico
               kableExtra) #Para tablas
```

```{r data}
data = readRDS("output/data/enut.rds")
```
 
```{r names}
sjPlot::view_df(data)
```

## Tabla de frecuencias con frq()

```{r}
frq(data$sexo)
```

### Personalicemos la tabla

```{r}
frq(data$sexo,
    title = "Distribución de la variable sexo",
    show.na = F,
    out = "viewer",
    encoding = "UTF-8",
    sort.frq = "asc") 
```

### Con kable

```{r}
frq(data$sexo,
    show.na = F,
    out = "viewer",
    encoding = "UTF-8",
    sort.frq = "asc") %>% 
  kable(caption = "Distribución de sexo",
        col.names = c("Valor", 
                      "Etiqueta",
                      "F. absoluta",
                      "F. relativa",
                      "F. relativa (valida)",
                      "F. rel. acumulada"))
```

### Con kable y dplyr

```{r}
data %>%
  select(sexo, quintil) %>% 
  frq(show.na = F,
      out = "viewer",
      encoding = "UTF-8",
      sort.frq = "asc") %>% 
  kable(caption = "Distribución de sexo y quintil",
        col.names = c("Valor", 
                      "Etiqueta",
                      "F. absoluta",
                      "F. relativa",
                      "F. relativa (valida)",
                      "F. rel. acumulada"))
```

### Con kableExtra
```{r}
data %>%
  select(sexo, quintil) %>% 
  frq(show.na = F,
      out = "viewer",
      encoding = "UTF-8",
      sort.frq = "asc") %>% 
  kable(caption = "Distribución de sexo y quintil",
        col.names = c("Valor", 
                      "Etiqueta",
                      "F. absoluta",
                      "F. relativa",
                      "F. relativa (valida)",
                      "F. rel. acumulada"),
        position = "center") %>% 
  kable_classic(full_width = F, html_font = "Cambria") 
```

### Con dplyr, kable y kableExtra

```{r}
frq(data$sexo,
    show.na = F,
    out = "viewer",
    encoding = "UTF-8",
    sort.frq = "asc") %>% 
  as.data.frame() %>% 
  select(val, frq, raw.prc, cum.prc) %>% #Seleccionamos columnas de interés
  mutate_at(vars(ends_with("prc")), 
                 ~(paste(., "%"))) %>% #Incorporamos porcentaje
  kable(caption = "Distribución de sexo",
        col.names = c("Sexo", 
                      "F. absoluta",
                      "F. relativa",
                      "F. rel. acumulada"),
        position = "center") %>% 
  kable_classic(full_width = F, html_font = "Cambria")
```

## Tabla de MTC con descr() 

```{r}
descr(data$traslado)
```

### Personalicemos la tabla

```{r}
descr(data$traslado,
      show = c("label", "n", "mean", "sd", "md", "range"))
```

### Con kable

```{r}
descr(data$traslado,
      show = c("label", "n", "mean", "sd", "md", "range")) %>% 
  kable()
```

### Presentemos dos variables

```{r}
data %>% 
  select(traslado, serv_nr_ds) %>% 
  descr(show = c("label", "n", "mean", "sd", "md", "range"))
```

### Con dplyr y kable

```{r}
data %>% 
  select(traslado, serv_nr_ds) %>% 
  descr(show = c("label", "n", "mean", "sd", "md", "range")) %>% 
  kable(caption = "MTC para tiempo de traslado y de trabajo no remunerado",
        col.names = c("Variable",
                      "Etiqueta",
                      "n", "Media",
                      "D. estandar",
                      "Mediana", "Rango"),
        position = "center")
```

### Con kableExtra

```{r}
data %>% 
  select(traslado, serv_nr_ds) %>% 
  descr(show = c("label", "n", "mean", "sd", "md", "range")) %>% 
  kable(format = "html",
        caption = "MTC para tiempo de traslado y de trabajo no remunerado",
        col.names = c("Variable",
                      "Etiqueta",
                      "n", "Media",
                      "D. estandar",
                      "Mediana", "Rango"),
        position = "center") %>% 
  kable_classic(full_width = F, html_font = "Cambria")  
```

### Con dplyr, kable y kableExtra

```{r}
data %>% 
  select(traslado, serv_nr_ds) %>% 
  descr(show = c("label", "n", "mean", "sd", "md", "range")) %>% 
  as.data.frame() %>% 
  mutate_at(vars(4, 5), ~(round(., digits = 3))) %>% 
  kable(format = "html",
        caption = "MTC para tiempo de traslado y de trabajo no remunerado",
        col.names = c("Variable",
                      "Etiqueta",
                      "n", "Media",
                      "D. estandar",
                      "Mediana", "Rango"),
        position = "center") %>% 
  kable_classic(full_width = F, html_font = "Cambria") 
```

## Likert

```{r}
plot_likert(data %>% select(starts_with("sat_")),
                            title = "Niveles de satisfacción con uso del tiempo",
                            catcount = 5,
                            reverse.scale = T) +
  geom_text_repel() # Para no solapar etiquetas
```

